### ISSUE TITLE
Camera control issue

### ISSUE THREAD

**Issue by fusi0nfire** [joshvillbrandt/GoProControllerUI#1]
Hey Josh,

I have the UI communicating with the API and it receives status from all of the GoPros attached.  I can send commands with the goproctl command line interface and the status updates correctly but the group control buttons on the webpage to not control the cameras.  I am running the latest commits

**Comment by joshvillbrandt** [comment]
Hey there,

I recently start refactoring this application and simply haven't finished re-implementing this feature. I should be able to finish this this week, however.

Thanks.

**Comment by fusi0nfire** [comment]
Josh,

Understood.  I have created a shell script in the meantime.  I am truly impressed with your work on this project.  I was looking for something this well written and well featured.  I may not have much to contribute as far as nodejs goes but I wanted to convey at least my gratitude to you for sharing this project in the open source community.

Thanks,
Darin

**Comment by fusi0nfire** [comment]
Hey @joshvillbrandt ,

Any luck with the refactor?  I was able to script using gopro ctrl.  I was wondering is there anything I can uncomment or help with in this regard?  I also have Hero 4 Blacks that use different control URL's and I can sniff the range of commands for you if that helps in dealing with the newest firmware release  for the Hero 4 Blacks.  If all of the GoPros do not get updated to the same control convention, it may be helpful to have a checkbox that gets selected when adding a camera via the UI/API indicating that the GoPro to be added uses different command format.  This [url](https://gist.github.com/KonradIT/ef320a13139d2cc077e8) shows a partial list of commands for the H4B.

-Regards

**Comment by joshvillbrandt** [comment]
Hey @fusi0nfire,

I spent the day doing the command refactor. Pull the latest and let me know what you think! (Also let me know if you find any bugs - I haven't actually tried these latest changes with an actual camera yet.)

Please post issues related to camera driver to the [goprohero](https://github.com/joshvillbrandt/goprohero/) library that this repo builds on. Also note that the cameras report which model they are and which firmware version they are using, so it is unlikely that a "checkbox" would be needed to support multiple camera APIs. The camera driver should be able to determine the appropriate API automatically.
